### PR TITLE
Task 2 refactored, utilising relativedelta to massively streamline the logic

### PR DESCRIPTION
**Pull request by okasen**
Taking into consideration the comments on my last PR, I refactored the task 2 logic to utilise the dateutil.relativedelta library instead of a mountain of if-statements. I also took into account some comments on type indication and class-parentheses rules. Of course, the tests are still passing!

### CODE REVIEW

File: tasks.py [hunk 1]
```diff
@@ -1,6 +1,7 @@
 import json
-from typing import Dict
+from typing import Dict, List
 import datetime
+from dateutil.relativedelta import *
```
Comment (stortiz-lifeworks) [inline tasks.py]: Using "import *" is considered a bad practice since it pollutes the namespace, this is, you include into the name space multiple definitions that could potentially clash with your own, or even with another "import *" from another library.

**Review by stortiz-lifeworks — APPROVED** [review]

File: tasks.py (hunk 1 above)
Comment (okasen) [reply tasks.py]: That makes a lot of sense. I'll add another commit importing relativedelta directly

**Comment by danballance** [comment]
@okasen looks really good to me, much approved :)
